### ISSUE TITLE
New Release Version

### ISSUE THREAD

**Issue by amitjoy** [rudin-io/s7connector#4]
I am wondering when there will be a new version of this library available in Maven Central.

**Comment by thomasrudin** [comment]
Just released v1.1
Should be available in the next hour via central:
```xml
<dependency>
    <groupId>io.rudin.s7connector</groupId>
    <artifactId>s7connector</artifactId>
    <version>1.1</version>
</dependency>
```

let me now if the bundle works for you, i have very little experience with osgi   :blush:
